version: '3'
services:
  web:
    build: .
    command: sh deploy/entry_point.sh
    depends_on:
      - db
    entrypoint: sh deploy/wait_for_postgres.sh
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    env_file:
      - .env
  db:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always